# Generated by Django 4.2.7 on 2026-01-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_captures/%Y/%m/%d/'),
        ),
    ]
