# Generated by Django 4.2.7 on 2026-05-07 18:11

from django.db import migrations, models
import django.utils.timezone


def backfill_session_date(apps, schema_editor):
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')
    for record in AttendanceRecord.objects.all().iterator():
        if record.marked_at:
            record.session_date = record.marked_at.date()
        record.save(update_fields=['session_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_captured_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='classsession',
            name='active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='daily_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='daily_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='key_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='schedule_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='schedule_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_session_date, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'class_session', 'session_date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['class_session', 'session_date'], name='attendance__class_s_37696c_idx'),
        ),
    ]
